[package]
name = "jehanni"
version = "0.1.0"
authors = ["yatabis <39yatabis.rim8820xxx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]